### All Setor:
http://localhost:8080/api/setor/

### Setor id 1
http://localhost:8080/api/setor/1

### Create Setor:
POST http://localhost:8080/api/setor HTTP/1.1
content-type: application/json

{
	"codigo": "CODIGOX",
	"nome": "Nome Setor",
	"lotacao": "01"
}

### Update Setor:
PUT http://localhost:8080/api/setor/26 HTTP/1.1
content-type: application/json

{
	"codigo": "NOVOCOD",
	"lotacao": "02"
}